#!/usr/bin/env bash


# DON'T install Node.JS with this Bootstrap script
# DON'T run hardware tests at this time
curl -sL http://ibm.biz/tjbot-bootstrap | sudo sh -

# install Node.JS 10.x & NPM
curl -sL https://deb.nodesource.com/setup_10.x | sudo bash
sudo apt install nodejs npm --yes

# upgrade NPM to 6.14.8
sudo npm install npm@latest -g
# remove old copy of NPM
sudo rm /usr/bin/npm
# verify NPM
echo $(which -a npm)
echo $(npm --version)

# force Node to 10.x
sudo rm /usr/local/bin/node
# verify NPM
echo $(which -a node)
echo $(node --version)

# verify NPM
echo $(which -a nodejs)
echo $(nodejs --version)

# install hardware dependencies
# assuming TJBot repo has been cloned to ~/Desktop/tjbot
sudo apt install --yes pigpio
npm install ~/Desktop/tjbot/bootstrap/tests

# test hardware
sudo ~/Desktop/tjbot/bootstrap/runTests.sh
