#!/usr/bin/env bash


TJBOT_TESTS_DIR_PATH=~/Desktop/tjbot/tests


cd $TJBOT_TESTS_DIR_PATH

# install hardware dependencies
# assuming TJBot repo has been cloned to ~/Desktop/tjbot
npm install

# test hardware components
sudo nodejs test.camera.js
sudo nodejs test.led.js
sudo nodejs test.mic.js
sudo nodejs test.servo.js
sudo nodejs test.speaker.js
