#!/usr/bin/env bash


# install hardware dependencies
# assuming TJBot repo has been cloned to ~/Desktop/tjbot
sudo apt install --yes pigpio
npm install ~/Desktop/tjbot/bootstrap/tests

# test hardware components
sudo ~/Desktop/tjbot/bootstrap/runTests.sh
