#!/usr/bin/env bash


# DON'T install Node.JS with this Bootstrap script
# DON'T run hardware tests at this time
curl -sL http://ibm.biz/tjbot-bootstrap | sudo sh -

# install Node.JS & NPM
sudo apt install nodejs npm

# upgrade NPM to 6.14.8
sudo npm i npm@latest -g
# remove old copy of NPM
sudo rm /usr/bin/npm 

# install hardware dependencies
# assuming TJBot repo has been cloned to ~/Desktop/tjbot
rm -rf node_modules
npm install ~/Desktop/tjbot/bootstrap/tests
